"""Vietnamese economic and financial abbreviations for TTS expansion."""

ECONOMIC_ABBREVIATIONS: dict[str, str] = {
    # Macroeconomic indicators
    "GDP": "Tổng sản phẩm quốc nội",
    "GNP": "Tổng sản phẩm quốc gia",
    "GNI": "Tổng thu nhập quốc gia",
    "CPI": "Chỉ số giá tiêu dùng",
    "PPI": "Chỉ số giá sản xuất",
    "PMI": "Chỉ số nhà quản trị mua hàng",
    "FDI": "Đầu tư trực tiếp nước ngoài",
    "FII": "Đầu tư gián tiếp nước ngoài",
    "ODA": "Hỗ trợ phát triển chính thức",
    "WTO": "Tổ chức Thương mại Thế giới",
    "IMF": "Quỹ Tiền tệ Quốc tế",
    "WB": "Ngân hàng Thế giới",
    "ADB": "Ngân hàng Phát triển Châu Á",
    # Vietnamese institutions
    "NHNN": "Ngân hàng Nhà nước",
    "NHTW": "Ngân hàng Trung ương",
    "NHTM": "Ngân hàng thương mại",
    "BTC": "Bộ Tài chính",
    "BKHDT": "Bộ Kế hoạch và Đầu tư",
    "TCTK": "Tổng cục Thống kê",
    "UBCKNN": "Ủy ban Chứng khoán Nhà nước",
    # Financial markets
    "TTCK": "Thị trường chứng khoán",
    "HOSE": "Sở Giao dịch Chứng khoán Thành phố Hồ Chí Minh",
    "HNX": "Sở Giao dịch Chứng khoán Hà Nội",
    "VNIndex": "Chỉ số VN Index",
    "VNXALL": "Chỉ số toàn thị trường",
    "ETF": "Quỹ hoán đổi danh mục",
    "IPO": "Phát hành cổ phiếu lần đầu ra công chúng",
    "EPS": "Lợi nhuận trên mỗi cổ phiếu",
    "PE": "Hệ số giá trên thu nhập",
    "PB": "Hệ số giá trên giá trị sổ sách",
    "ROE": "Tỷ suất lợi nhuận trên vốn chủ sở hữu",
    "ROA": "Tỷ suất lợi nhuận trên tổng tài sản",
    # Financial statements and accounting
    "BCTC": "Báo cáo tài chính",
    "KQKD": "Kết quả kinh doanh",
    "LCTT": "Lưu chuyển tiền tệ",
    "CDKT": "Cân đối kế toán",
    "LNST": "Lợi nhuận sau thuế",
    "LNTT": "Lợi nhuận trước thuế",
    "VCSH": "Vốn chủ sở hữu",
    "EBITDA": "Lợi nhuận trước lãi vay, thuế và khấu hao",
    # Banking and monetary
    "LSCB": "Lãi suất cơ bản",
    "LSTCV": "Lãi suất tái cấp vốn",
    "LSCK": "Lãi suất chiết khấu",
    "TPCP": "Trái phiếu Chính phủ",
    "TPDN": "Trái phiếu doanh nghiệp",
    "NPL": "Nợ xấu",
    "CAR": "Hệ số an toàn vốn",
    # Trade and commerce
    "XK": "Xuất khẩu",
    "NK": "Nhập khẩu",
    "XNK": "Xuất nhập khẩu",
    "CCTM": "Cán cân thương mại",
    "FTA": "Hiệp định thương mại tự do",
    "RCEP": "Hiệp định Đối tác Kinh tế Toàn diện Khu vực",
    "CPTPP": "Hiệp định Đối tác Toàn diện và Tiến bộ xuyên Thái Bình Dương",
    "EVFTA": "Hiệp định Thương mại tự do Việt Nam - EU",
    # Currency
    "VND": "Việt Nam đồng",
    "USD": "Đô la Mỹ",
    "EUR": "Euro",
    "JPY": "Yên Nhật",
    "CNY": "Nhân dân tệ",
    # Business and corporate
    "DN": "Doanh nghiệp",
    "DNNN": "Doanh nghiệp nhà nước",
    "DNNVV": "Doanh nghiệp nhỏ và vừa",
    "ĐHĐCĐ": "Đại hội đồng cổ đông",
    "HĐQT": "Hội đồng quản trị",
    "TGĐ": "Tổng giám đốc",
    "CEO": "Giám đốc điều hành",
    "CFO": "Giám đốc tài chính",
    # Tax and fiscal
    "GTGT": "Giá trị gia tăng",
    "VAT": "Thuế giá trị gia tăng",
    "TNDN": "Thu nhập doanh nghiệp",
    "TNCN": "Thu nhập cá nhân",
    "NSNN": "Ngân sách nhà nước",
}
